# Form implementation generated from reading ui file 'src/views/showinthebox/showinthebox.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShowintheboxForm(object):
    def setupUi(self, ShowintheboxForm):
        ShowintheboxForm.setObjectName("ShowintheboxForm")
        ShowintheboxForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        ShowintheboxForm.resize(1090, 370)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShowintheboxForm.sizePolicy().hasHeightForWidth())
        ShowintheboxForm.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShowintheboxForm)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startnumTableView = QtWidgets.QTableView(parent=ShowintheboxForm)
        self.startnumTableView.setSortingEnabled(True)
        self.startnumTableView.setObjectName("startnumTableView")
        self.verticalLayout.addWidget(self.startnumTableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Counterlabel = QtWidgets.QLabel(parent=ShowintheboxForm)
        self.Counterlabel.setObjectName("Counterlabel")
        self.horizontalLayout.addWidget(self.Counterlabel)
        self.counterValuelabel = QtWidgets.QLabel(parent=ShowintheboxForm)
        self.counterValuelabel.setObjectName("counterValuelabel")
        self.horizontalLayout.addWidget(self.counterValuelabel)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startnumlabel = QtWidgets.QLabel(parent=ShowintheboxForm)
        self.startnumlabel.setObjectName("startnumlabel")
        self.horizontalLayout.addWidget(self.startnumlabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.startnumLineEdit = QtWidgets.QLineEdit(parent=ShowintheboxForm)
        self.startnumLineEdit.setObjectName("startnumLineEdit")
        self.horizontalLayout.addWidget(self.startnumLineEdit)
        self.closePushButton = QtWidgets.QPushButton(parent=ShowintheboxForm)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout.addWidget(self.closePushButton)
        self.horizontalLayout.setStretch(2, 8)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.statusBar = QtWidgets.QLabel(parent=ShowintheboxForm)
        self.statusBar.setText("")
        self.statusBar.setObjectName("statusBar")
        self.verticalLayout.addWidget(self.statusBar)

        self.retranslateUi(ShowintheboxForm)
        QtCore.QMetaObject.connectSlotsByName(ShowintheboxForm)

    def retranslateUi(self, ShowintheboxForm):
        _translate = QtCore.QCoreApplication.translate
        ShowintheboxForm.setWindowTitle(_translate("ShowintheboxForm", "show in the box"))
        self.Counterlabel.setText(_translate("ShowintheboxForm", "counter"))
        self.counterValuelabel.setText(_translate("ShowintheboxForm", "0"))
        self.startnumlabel.setText(_translate("ShowintheboxForm", "Startnum"))
        self.closePushButton.setText(_translate("ShowintheboxForm", "Close"))
