# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showinthebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowintheboxForm(object):
    def setupUi(self, ShowintheboxForm):
        ShowintheboxForm.setObjectName("ShowintheboxForm")
        ShowintheboxForm.setWindowModality(QtCore.Qt.WindowModal)
        ShowintheboxForm.resize(1090, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShowintheboxForm.sizePolicy().hasHeightForWidth())
        ShowintheboxForm.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(ShowintheboxForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.startnumTableView = QtWidgets.QTableView(ShowintheboxForm)
        self.startnumTableView.setSortingEnabled(True)
        self.startnumTableView.setObjectName("startnumTableView")
        self.gridLayout.addWidget(self.startnumTableView, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Counterlabel = QtWidgets.QLabel(ShowintheboxForm)
        self.Counterlabel.setObjectName("Counterlabel")
        self.horizontalLayout.addWidget(self.Counterlabel)
        self.counterValuelabel = QtWidgets.QLabel(ShowintheboxForm)
        self.counterValuelabel.setObjectName("counterValuelabel")
        self.horizontalLayout.addWidget(self.counterValuelabel)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startnumlabel = QtWidgets.QLabel(ShowintheboxForm)
        self.startnumlabel.setObjectName("startnumlabel")
        self.horizontalLayout.addWidget(self.startnumlabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.startnumLineEdit = QtWidgets.QLineEdit(ShowintheboxForm)
        self.startnumLineEdit.setObjectName("startnumLineEdit")
        self.horizontalLayout.addWidget(self.startnumLineEdit)
        self.horizontalLayout.setStretch(2, 8)
        self.horizontalLayout.setStretch(5, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.statusBar = QtWidgets.QLabel(ShowintheboxForm)
        self.statusBar.setText("")
        self.statusBar.setObjectName("statusBar")
        self.gridLayout_2.addWidget(self.statusBar, 1, 0, 1, 1)

        self.retranslateUi(ShowintheboxForm)
        QtCore.QMetaObject.connectSlotsByName(ShowintheboxForm)

    def retranslateUi(self, ShowintheboxForm):
        _translate = QtCore.QCoreApplication.translate
        ShowintheboxForm.setWindowTitle(_translate("ShowintheboxForm", "show in the box"))
        self.Counterlabel.setText(_translate("ShowintheboxForm", "counter"))
        self.counterValuelabel.setText(_translate("ShowintheboxForm", "0"))
        self.startnumlabel.setText(_translate("ShowintheboxForm", "Startnum"))
